/* DELETE 'carsdb' database*/
DROP SCHEMA IF EXISTS carsdb;
/* DELETE USER 'spq' AT LOCAL SERVER*/
DROP USER IF EXISTS 'spq'@'%';



/* CREATE 'carsdb' DATABASE */
CREATE SCHEMA carsdb;
/* CREATE THE USER 'spq' AT LOCAL SERVER WITH PASSWORD 'spq' */
CREATE USER IF NOT EXISTS 'spq'@'%' IDENTIFIED BY 'spq';
/* GRANT FULL ACCESS TO THE DATABASE FOR THE USER 'spq' AT LOCAL SERVER*/
GRANT ALL ON carsdb.* TO 'spq'@'%';

